language: node_js

node_js:
    - 13

services:
    - docker

env:
    - DOCKER_COMPOSE_VERSION=1.23.2

install:
    - echo "nothing needs to be installed"

before_script:
    - echo "no tests"

script:
    - docker -v && docker-compose -v

after_success:
    - echo "SUCCESS"