version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: garcialuiz/udagram-reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image:  garcialuiz/udagram-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image:  garcialuiz/udagram-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image:  garcialuiz/udagram-frontend:local
